cache:
  paths:
    - backend/.gradle/wrapper
    - backend/.gradle/caches

stages:
  - build
  - test
  - docker
  - sonarqube-check

backend-build:
  stage: build
  script:
    - cd backend
    - ./gradlew assemble --no-daemon

frontend-build:
  stage: build
  script:
    - cd frontend
    - pnpm install --frozen-lockfile
    - pnpm run build

backend-test:
  stage: test
  script:
    - cd backend
    - ./gradlew test --no-daemon

frontend-test:
  stage: test
  script:
    - cd frontend
    - pnpm install --frozen-lockfile
    - pnpm check
    - pnpm test

docker-backend:
  stage: docker
  script:
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/backend:latest" ./backend
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"

docker-frontend:
  stage: docker
  script:
    - echo "CI_REGISTRY=$CI_REGISTRY"
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/frontend:latest" ./frontend
    - docker push "$CI_REGISTRY_IMAGE/frontend:latest"

sonarqube-check:
  stage: sonarqube-check
  script:
    - echo "This is a demo stage replacing SonarQube analysis"

