services:
  backend:
    image: shellyfourer/freelance-tax-manager-backend:latest
    container_name: tax-manager-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    image: shellyfourer/freelance-tax-manager-frontend:latest
    container_name: tax-manager-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend